//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGOCollection.library.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class refCardList
    {
        public short ID { get; set; }
        public string code { get; set; }
        public string packname { get; set; }
        public Nullable<short> piece { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
    }
}
