//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGOCollection.library.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YGOCardInfoEntities : DbContext
    {
        public YGOCardInfoEntities()
            : base("name=YGOCardInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<refAttribute> refAttributes { get; set; }
        public virtual DbSet<refCardList> refCardLists { get; set; }
        public virtual DbSet<refCardType> refCardTypes { get; set; }
        public virtual DbSet<refMonsterType> refMonsterTypes { get; set; }
        public virtual DbSet<YGOMonster> YGOMonsters { get; set; }
        public virtual DbSet<YGOSpell> YGOSpells { get; set; }
        public virtual DbSet<YGOTrap> YGOTraps { get; set; }
    }
}
